# v2 sintax
version: '2'

services:

  app:
    image: allanzi/node:latest
    container_name: app
    command: bash -c "npm i && npm start"
    volumes:
      - .:/var/www/app
    ports:
      - 8000:8000